{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atelier.componentName" (dict "root" $ "component" "redis") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atelier.labels" $ | nindent 4 }}
    {{- include "atelier.selectorLabels" (dict "root" $ "component" "redis") | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    {{- include "atelier.selectorLabels" (dict "root" $ "component" "redis") | nindent 4 }}
{{- end }}
