{{- if and .Values.s3Storage.rustfs.enabled (not .Values.s3Storage.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atelier.componentName" (dict "root" $ "component" "rustfs") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atelier.labels" $ | nindent 4 }}
    {{- include "atelier.selectorLabels" (dict "root" $ "component" "rustfs") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: s3-api
      port: {{ .Values.s3Storage.rustfs.service.port }}
      targetPort: s3-api
  selector:
    {{- include "atelier.selectorLabels" (dict "root" $ "component" "rustfs") | nindent 4 }}
{{- end }}
