{{- if and .Values.keycloak.enabled (not .Values.keycloak.external.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "atelier.componentName" (dict "root" $ "component" "keycloak") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atelier.labels" $ | nindent 4 }}
  annotations:
    {{- include "atelier.certManagerAnnotation" $ | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.domains.keycloak }}
      secretName: {{ printf "%s-tls" (include "atelier.componentName" (dict "root" $ "component" "keycloak")) }}
  {{- end }}
  rules:
    - host: {{ .Values.domains.keycloak }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "atelier.componentName" (dict "root" $ "component" "keycloak") }}
                port:
                  number: {{ .Values.keycloak.service.port }}
{{- end }}
